title: Dragone Editor Document
email: lovefield@dico.me
description: Dragone Editor Document site
baseurl: "/dragonEditor-doc"
url: ""
versionList : ["1.0.2"]
langList : ["ko", "en"]
lang : "en"
lastset : "1.0.3"

# Build settings
theme: minima
